add pickling (#258)
* Delete pickler.py

* add `__reduce__` to ensure pickling works for all attributes

Without `__reduce__`, the input params of `__init__` might not be pickled, e.g. `id`.

* add `save_links` method

* Update test_nplinker_local.py

* update `save_data` method to ensure consistent return

* fix error caused by NumPy 2.0

AttributeError: `np.NINF` was removed in the NumPy 2.0 release. Use `-np.inf` instead.